In [1]:
import numpy as np
import pandas as pd
import math
import gc

In [2]:
file = r'./data_compressed.csv'
df = pd.read_csv(file)

In [4]:
df['occurence']=1

In [6]:
df.groupby(['sex','current_data_year', 'month_of_death', 'age','education'], sort=True).occurence.sum().reset_index()

      sex  current_data_year  month_of_death  age  education  occurence
0       F               2005               1    1        0.0        722
1       F               2005               1    1        1.0        422
2       F               2005               1    1        3.0         56
3       F               2005               1    2        0.0         66
4       F               2005               1    2        1.0         51
5       F               2005               1    2        3.0         13
6       F               2005               1    3        0.0         58
7       F               2005               1    3        1.0         59
8       F               2005               1    3        3.0         10
9       F               2005               1    4        0.0         19
10      F               2005               1    4        1.0        239
11      F               2005               1    4        2.0         27
12      F               2005               1    4        3.0         15
13      F               2005               1    5        0.0         12
14      F               2005               1    5        1.0        314
15      F               2005               1    5        2.0         81
16      F               2005               1    5        3.0         20
17      F               2005               1    6        0.0         13
18      F               2005               1    6        1.0        317
19      F               2005               1    6        2.0         94
20      F               2005               1    6        3.0         22
21      F               2005               1    7        0.0         16
22      F               2005               1    7        1.0        447
23      F               2005               1    7        2.0        122
24      F               2005               1    7        3.0         33
25      F               2005               1    8        0.0         34
26      F               2005               1    8        1.0        704
27      F               2005               1    8        2.0        198
28      F               2005               1    8        3.0         48
29      F               2005               1    9        0.0         58
...    ..                ...             ...  ...        ...        ...
19349   M               2014              12   14        3.0         24
19350   M               2014              12   15        0.0         75
19351   M               2014              12   15        1.0      12433
19352   M               2014              12   15        2.0        268
19353   M               2014              12   15        3.0         21
19354   M               2014              12   16        0.0        125
19355   M               2014              12   16        1.0      13437
19356   M               2014              12   16        2.0        290
19357   M               2014              12   16        3.0         13
19358   M               2014              12   17        0.0        155
19359   M               2014              12   17        1.0      15125
19360   M               2014              12   17        2.0        320
19361   M               2014              12   17        3.0         11
19362   M               2014              12   18        0.0        149
19363   M               2014              12   18        1.0      15218
19364   M               2014              12   18        2.0        352
19365   M               2014              12   18        3.0         16
19366   M               2014              12   19        0.0         84
19367   M               2014              12   19        1.0      10259
19368   M               2014              12   19        2.0        229
19369   M               2014              12   19        3.0          8
19370   M               2014              12   20        0.0         32
19371   M               2014              12   20        1.0       3078
19372   M               2014              12   20        2.0         82
19373   M               2014              12   20        3.0          3
19374   M               2014              12   21        0.0          6
19375   M               2014              12   21        1.0        459
19376   M               2014              12   21        2.0          7
19377   M               2014              12   21        3.0          2
19378   M               2014              12   22        1.0         13

[19379 rows x 6 columns]