In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
import statsmodels.api as sm

In [5]:
file = r'C:\Final Project\Final Data\counter.csv'
df = pd.read_csv(file)

In [6]:
df_sex = pd.get_dummies(df['sex'],prefix='sex')
df_year = df['current_data_year'] - 2004
df_month = df['month_of_death']
df_edu = pd.get_dummies(df['education'],prefix = 'edu')
df_edu.columns = ['primary or less','high school','college or higher','edu not stated']
df_age = pd.get_dummies(df['age'],prefix='age')
df_age.columns = ['age_0-4','age_5-9','age_10-14','age_15-19','age_20-24','age_25-29','age_30-34','age_35-39','age_40-44','age_45-49','age_50-54','age_55-59','age_60-64','age_65-69','age_70-74','age_75-79','age_80-84','age_85-89','age_90-94','age_95-99','age_100 and over','age_not_stated']
df_act = pd.get_dummies(df['activity'],prefix='activity')
df_race = pd.get_dummies(df['race'],prefix='race')

In [7]:
df_year_cub = df_year ** (0.33)
df_year_sqrt = np.sqrt(df_year)
df_year_2 = (df_year)**2
df_year_3 = (df_year)**3
df_year_4 = (df_year)**4
df_month_cub = df_month ** (0.33)
df_month_sqrt = np.sqrt(df_month)
df_month_2 = (df_month)**2
df_month_3 = (df_month)**3
df_month_4 = (df_month)**4
df_year = pd.concat([df_year,df_year_cub,df_year_sqrt,df_year_2,df_year_3,df_year_4],axis = 1,join_axes=[df_year.index])
df_month = pd.concat([df_month,df_month_cub,df_month_sqrt,df_month_2,df_month_3,df_month_4],axis = 1,join_axes=[df_month.index])
df_year.columns = ['year','year^0.33','year^0.5','year^2', 'year^3', 'year^4']
df_month.columns = ['month','month^0.33','month^0.5','month^2', 'month^3', 'month^4']

In [8]:
data = pd.concat([df_sex,df_year,df_month,df_age,df_act,df_race,df_edu,df['ICD'],df['occurence']],axis = 1,join_axes=[df_sex.index])

In [9]:
data

,sex_F,sex_M,year,year^0.33,year^0.5,year^2,year^3,year^4,month,month^0.33,...,race_1,race_2,race_3,race_4,primary or less,high school,college or higher,edu not stated,ICD,occurence
0,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,20,48
1,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,20,22
2,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,0,1,0,1,0,0,0,20,1
3,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,0,0,1,1,0,0,0,20,1
4,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,1,8
5,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,2,11
6,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,3,2
7,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,4,6
8,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,6,12
9,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,9,13
10,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,10,12
11,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,11,12
12,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,14,5
13,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,16,180
14,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,17,114
15,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,1,0,0,0,1,0,0,0,18,48
16,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,1,8
17,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,2,1
18,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,3,1
19,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,4,1
20,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,6,4
21,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,9,5
22,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,10,8
23,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,11,6
24,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,14,3
25,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,16,103
26,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,17,31
27,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,1,0,0,1,0,0,0,18,29
28,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,0,1,0,1,0,0,0,1,1
29,1,0,1,1.000000,1.000000,1,1,1,1,1.000000,...,0,0,1,0,1,0,0,0,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499775,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,1,0,0,18,17
499776,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,1,1
499777,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,2,6
499778,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,5,2
499779,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,6,3
499780,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,9,13
499781,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,10,2
499782,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,14,3
499783,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,18,1
499784,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,1,1
499785,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,2,2
499786,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,4,1
499787,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,5,1
499788,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,6,2
499789,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,9,6
499790,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,10,2
499791,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,11,1
499792,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,0,0,1,0,1,0,0,14,1
499793,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,0,1,0,5,1
499794,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,0,1,0,9,2
499795,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,0,1,0,10,3
499796,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,0,1,0,14,1
499797,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,0,0,1,10,2
499798,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,1,0,0,20,1
499799,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,1,0,0,9,2
499800,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,1,0,0,11,1
499801,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,1,0,0,0,0,1,0,0,18,5
499802,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,9,2
499803,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,10,1
499804,0,1,10,2.137962,3.162278,100,1000,10000,12,2.270543,...,0,1,0,0,0,1,0,0,11,1

In [12]:
# set the data["ICD"] to the type being analyzed
table = shuffle(data[data['ICD']==20])
X = table.iloc[:,:-2]
y = table['occurence']
X = sm.add_constant(X)
model = sm.GLM(y, X, family=sm.families.Poisson()).fit()
print (model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:              occurence   No. Observations:                63612
Model:                            GLM   Df Residuals:                    63564
Model Family:                 Poisson   Df Model:                           47
Link Function:                    log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -3.3022e+05
Date:                Tue, 10 Dec 2019   Deviance:                   4.3628e+05
Time:                        11:39:59   Pearson chi2:                 6.90e+05
No. Iterations:                   100   Covariance Type:             nonrobust
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                47.0014      2.837     16.567      0.000      41.441      52.562
sex_F                23.1362      1.419     16.310      0.000      20.356      25.917
sex_M                23.8652      1.419     16.823      0.000      21.085      26.646
year                -28.5750      2.986     -9.569      0.000     -34.428     -22.722
year^0.33          -222.1546     23.074     -9.628      0.000    -267.380    -176.930
year^0.5            198.0520     20.578      9.625      0.000     157.721     238.383
year^2                1.3831      0.149      9.288      0.000       1.091       1.675
year^3               -0.0737      0.008     -8.852      0.000      -0.090      -0.057
year^4                0.0019      0.000      8.391      0.000       0.001       0.002
month               -26.5616      1.558    -17.050      0.000     -29.615     -23.508
month^0.33         -225.7704     12.854    -17.564      0.000    -250.965    -200.576
month^0.5           196.5189     11.285     17.414      0.000     174.400     218.637
month^2               1.1624      0.069     16.781      0.000       1.027       1.298
month^3              -0.0577      0.003    -16.955      0.000      -0.064      -0.051
month^4               0.0014   7.86e-05     17.284      0.000       0.001       0.002
age_0-4               1.7481      0.129     13.544      0.000       1.495       2.001
age_5-9               0.5282      0.129      4.085      0.000       0.275       0.782
age_10-14             0.9201      0.129      7.121      0.000       0.667       1.173
age_15-19             2.5696      0.129     19.918      0.000       2.317       2.822
age_20-24             3.0770      0.129     23.854      0.000       2.824       3.330
age_25-29             3.0069      0.129     23.310      0.000       2.754       3.260
age_30-34             2.9071      0.129     22.535      0.000       2.654       3.160
age_35-39             2.9000      0.129     22.481      0.000       2.647       3.153
age_40-44             3.0233      0.129     23.437      0.000       2.771       3.276
age_45-49             3.1550      0.129     24.459      0.000       2.902       3.408
age_50-54             3.1325      0.129     24.284      0.000       2.880       3.385
age_55-59             2.9239      0.129     22.666      0.000       2.671       3.177
age_60-64             2.6074      0.129     20.211      0.000       2.355       2.860
age_65-69             2.3531      0.129     18.238      0.000       2.100       2.606
age_70-74             2.2814      0.129     17.682      0.000       2.028       2.534
age_75-79             2.4240      0.129     18.788      0.000       2.171       2.677
age_80-84             2.6308      0.129     20.392      0.000       2.378       2.884
age_85-89             2.6586      0.129     20.608      0.000       2.406       2.911
age_90-94             2.2889      0.129     17.740      0.000       2.036       2.542
age_95-99             1.3577      0.129     10.516      0.000       1.105       1.611
age_100 and over     -0.1606      0.130     -1.238      0.216      -0.415       0.094
age_not_stated       -1.3316      0.132    -10.090      0.000      -1.590      -1.073
activity_0.0          5.3267      0.356     14.975      0.000       4.630       6.024
activity_1.0          4.7734      0.356     13.411      0.000       4.076       5.471
activity_2.0          4.9567      0.356     13.940      0.000       4.260       5.654
activity_3.0          4.5224      0.364     12.424      0.000       3.809       5.236
activity_4.0          5.1159      0.356     14.375      0.000       4.418       5.813
activity_8.0          4.7636      0.356     13.382      0.000       4.066       5.461
activity_9.0         10.3946      0.355     29.290      0.000       9.699      11.090
activity_10.0         7.1481      0.355     20.141      0.000       6.453       7.844
race_1               14.0573      0.709     19.819      0.000      12.667      15.447
race_2               12.2571      0.709     17.281      0.000      10.867      13.647
race_3               10.2115      0.709     14.397      0.000       8.821      11.602
race_4               10.4756      0.709     14.769      0.000       9.085      11.866
primary or less      10.9227      0.709     15.399      0.000       9.533      12.313
high school          13.9349      0.709     19.646      0.000      12.545      15.325
college or higher    11.7908      0.709     16.623      0.000      10.401      13.181
edu not stated       10.3530      0.709     14.596      0.000       8.963      11.743
=====================================================================================